bq_migration_config={'project':'michael-gilbert-dev',
                     'preprocessed':'gs://dwh_preprocessed',
                     'source_sql':f'source_sql/',
                     'uc4_git_repo':'https://github.com/RealistAI/UC4_SQL.git',
                     'translated':'gs://dwh_translated',
                     'transpiled_sql':'transpiled_sql/',
                     'dwh_config':'config/config.yaml',
                     'mapping_config':'config/name_mapping.json',
                     'debug_mode':True}
